name: Run

on:
  workflow_dispatch:
    inputs:
      pull_request_sha: 
        type: string
        required: true
        description: Test
  workflow_call:
    inputs:
      pull_request_sha: 
        type: string
        required: true
        description: Test

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo ${{ inputs.pull_request_sha }}
          echo "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Checkout selected branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - uses: tibdex/github-app-token@v1
        id: get_installation_token
        if: always()
        with: 
          app_id: 293149
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Show results in PR
        uses: LouisBrunner/checks-action@v1.6.0
        if: always()
        with:
          name: E2E Tests - Staging
          repo: aryella-lacerda/ci-testing
          details_url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          sha: ${{ inputs.pull_request_sha }}
          token: ${{ steps.get_installation_token.outputs.token }}
          conclusion: ${{ job.status }}