name: Run

on:
  workflow_dispatch:
    inputs:
      pull_request_sha: 
        type: string
        required: true
        description: Test
  workflow_call:
    inputs:
      pull_request_sha: 
        type: string
        required: true
        description: Test

jobs:
  run-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo ${{ inputs.pull_request_sha }}
          echo "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Checkout selected branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - run: sleep 60s

      - uses: tibdex/github-app-token@v1
        id: get_installation_token
        if: always()
        with: 
          app_id: 293149
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create PR check for E2E Tests
        uses: actions/github-script@v6
        with:
          github-token: ${{ steps.get_installation_token.outputs.token }}
          script: |
            github.rest.checks.create({
              owner: "aryella-lacerda",
              repo: "ci-testing",
              name: "E2E Tests - Staging",
              head_sha: "${{ inputs.pull_request_sha }}",
              conclusion: "${{ job.status }}"
            })